variables:
  APP_IMAGE: "osl_app"
  COMPOSE_FILE: "docker-compose.build.yml"
  CONTAINER_RELEASE_IMAGE: "nanawel/our-shopping-list"

stages:
  - check
  - build
  - release

before_script:
  - time docker info
  - time docker login ${REGISTRY_SERVER}

build_image:
  stage: build
  script:
    - time make config
    - time make build args="--build-arg build_version=${CI_COMMIT_REF_SLUG} --build-arg build_id=${CI_COMMIT_SHORT_SHA} --build-arg build_date=$(date -Is)"
    - time docker tag ${APP_IMAGE}:${APP_VERSION:-latest} ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker push ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
  tags:
    - shell
    - docker

push_image_latest:
  stage: release
  script:
    - time docker pull ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_RELEASE_IMAGE}:latest
    - time docker push ${CONTAINER_RELEASE_IMAGE}:latest
  tags:
    - shell
    - docker
  only:
    - master

push_image_tagged:
  stage: release
  script:
    - time docker pull ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_REF_SLUG}
    - time docker push ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_REF_SLUG}
  tags:
    - shell
    - docker
  only:
    - /^\d+\.\d+\.\d+.*
