version: '3.2'

services:
  app:
    image: nanawel/our-shopping-list:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4-bionic
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: