version: '3.2'

services:
  app:
    image: ourshoppinglist/our-shopping-list:latest
    restart: always
    ports:
      - '8080:8080'
    environment:
      # Default values below (See README for more)
      VUE_APP_I18N_LOCALE: en
      VUE_APP_I18N_FALLBACK_LOCALE: en
      VUE_APP_I18N_FORCE_LOCALE: 0
      VUE_APP_SINGLEBOARD_MODE: 0
    # You may want to use a .env file instead
    #env_file:
    #  - .env
    #volumes:
    #  - ./robots.txt:/app/robots.txt:ro   # See README
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
